dist: trusty
language: elixir
# sudo: true
sudo: false

jdk: openjdk8

elixir:
  - '1.7.3'
otp_release: '21.0'

install:
  - echo "passing..."
  # - git clone --branch 1.6.2 https://githucom/appulse-projects/encon-java.git
  # - cd encon-java
  # - mvn install -DskipTests=true

before_script:
  - echo "passing..."

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2

script:
  - cd ${TRAVIS_BUILD_DIR}
  - ./run_all.sh
