dist: trusty
language: elixir
# sudo: true
sudo: false

jdk: openjdk8

elixir:
  - '1.7.3'
otp_release: '21.0'

install:
  - echo "passing..."
  # - wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb
  # - sudo apt-get update && sudo apt-get install elixir

before_script:
  - echo "passing..."

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./run_all.sh
